# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "SDKDemo" do
 
 pod 'ProxibleSDK', :git => 'https://github.com/Proxible/Proxible-ios-sdk.git'
 
end

target "SDKDemoTests" do

end

